module.exports = {
  "extends": [
    ":assignAndReview(pujanshah3333)",
    ":autodetectPinVersions",
    ":automergeBranch",
    ":automergeMinor",
    ":automergeRequireAllStatusChecks",
    ":combinePatchMinorReleases",
    ":dependencyDashboard",
    ":enableVulnerabilityAlerts",
    ":ignoreModulesAndTests",
    ":ignoreUnstable",
    ":label(renovate)",
    ":prNotPending",
    ":renovatePrefix",
    ":separateMultipleMajorReleases",
    ":updateNotScheduled",
    "group:monorepos",
    "group:recommended",
    "workarounds:all",
  ],
  commitMessagePrefix: '[renovate]',
  deepExtract: true,
  dependencyDashboardAutoclose: true,
  docker: { pinDigests: true },
  exposeAllEnv: true,
  labels: ['renovate'],
  onboarding: false,
  platform: 'github',
  requireConfig: false,
  schedule: null,
  updateLockFiles: true,
  hostRules: [
    {
      hostType: 'maven',
      matchHost: 'https://maven.pkg.github.com/',
      token: process.env.GITHUB_TOKEN,
    },
  ],
  packageRules: [
    {
      matchUpdateTypes: ['major'],
      labels: ['major-update'],
      automerge: false,
    },
    {
      extends: ['group:springBoot'],
      automerge: false,
    },
    {
      'matchPackageNames': ['com.github.spotbugs:com.github.spotbugs.gradle.plugin'],
      'allowedVersions': '> 5.0.1'
    },
    {
      matchUpdateTypes: ['minor', 'patch'],
      matchCurrentVersion: '!/^0/',
      automerge: true,
      automergeType: 'branch',
      labels: ['automerge'],
    },
    {
      matchManagers: ['dockerfile'],
      additionalBranchPrefix: 'docker-',
      groupName: 'docker',
      labels: ['docker'],
    },
    {
      matchDatasources: ['docker'],
      additionalBranchPrefix: 'docker-',
      groupName: 'docker',
      labels: ['docker'],
    },
    {
      matchDatasources: ['git-refs', 'git-tags', 'github-releases', 'github-tags'],
      additionalBranchPrefix: 'git-',
      groupName: 'git',
    },
    {
      matchManagers: ['gradle'],
      additionalBranchPrefix: 'java-',
      groupName: 'java',
      labels: ['java'],
    },
    {
      matchDatasources: ['gradle-version'],
      additionalBranchPrefix: 'gradle-',
      labels: ['java'],
    },
    {
      matchDatasources: ['npm'],
      additionalBranchPrefix: 'npm-',
      groupName: 'npm',
      labels: ['javascript'],
    },
    {
      matchManagers: ['terraform'],
      additionalBranchPrefix: 'terraform-',
      groupName: 'terraform',
      labels: ['terraform'],
    },
  ],
};
